### ISSUE TITLE
batchsize

### ISSUE THREAD

**Issue by nationalflag** [L1aoXingyu/reid_baseline#10]
为什么batchsize小结果还更好呢？

**Comment by d-li14** [comment]
when using batch size 128, it is necessary to use two gpus for enough memory?

**Comment by PayneYong** [comment]
看到有些观点是batchsize的大小对结果也是有影响的，batchsize大了可能收敛的快点，但对准确率而言并不是越大越好。

**Comment by L1aoXingyu** [comment]
如果 (384, 128)，使用 batch size=128，显存应该会占到 15G 左右，但是目前发现 (256, 128) 效果更好，同时 batch size 64 效果更好，感觉是因为 batch size 比较小容易跳出local minimal，而且 triplet loss 对 32个 id 和 16 个 id，并不是特别 sensitive，本来就是 hard sample

**Comment by PayneYong** [comment]
在知乎上加了bottleneck结构，Linear(2048, 512) -> bn -> LeakyReLU(0.1) -> Dropout(0.5)，看你你代码好像并不是这样做的，实际上你只用到了一个批标准化是吧

**Comment by L1aoXingyu** [comment]
那个依旧是老结构了，现在的新结构轻松秒杀以前的bottleneck，而且使用bn前面的feature，用cosine距离测试还可以再涨点，这个结果不就会post上来

**Comment by L1aoXingyu** [comment]
只是懒得做了，你可以自己跑一下

Bests,
Xingyu

**Comment by PayneYong** [comment]
多谢
