### ISSUE TITLE
Why did you remove the first relu of ResNet?

### ISSUE THREAD

**Issue by Yououko** [L1aoXingyu/reid_baseline#12]
Thanks for your work.
Why did you remove the first relu in ResNet in `modeling/backbones/resnet.py`? Does removing it make the result better?

**Comment by L1aoXingyu** [comment]
I did not remove the first relu in ResNet, this ResNet is just the same as `torchvision.models.resnet50`, except that I change the last stride in the last block's conv.

**Comment by L1aoXingyu** [comment]
This is my fault. Actually, I missed the first relu in ResNet. I train the model with relu again, and I can get almost the same results. I will add it soon.
