### ISSUE TITLE
cuhk03训练

### ISSUE THREAD

**Issue by PayneYong** [L1aoXingyu/reid_baseline#14]
你好，请问如何在cuhk03数据集上训练

**Comment by PayneYong** [comment]
python3 tools/train.py --config_file='configs/softmax.yml' DATASETS.NAMES "('cuhk03')"
报错：RuntimeError: '/home/payne/Dataset/L1aoXingyu/cuhk03/cuhk03_new_protocol_config_detected.mat' is not available

**Comment by PayneYong** [comment]
在market1501和duke上代码都能执行，但是在cuhk03上训练就是不行，执行命令：python3 tools/train.py --config_file='configs/softmax.yml' DATASETS.NAMES "('cuhk03')"后报错如下：
RuntimeError: '/home/payne/Dataset/L1aoXingyu/cuhk03/cuhk03_new_protocol_config_detected.mat' is not available，这个问题都问了很久了，楼主有时间能回复下吗，由于本人不是做这块的，不懂的太多，希望楼主能帮帮忙。

**Comment by L1aoXingyu** [comment]
应该是你的路径有问题

**Comment by PayneYong** [comment]
我的路径是这样的：cuhk03|cuhk03_release|cuhk03.mat，是不是缺了什么东西

**Comment by L1aoXingyu** [comment]
改成 cuhk03|cuhk03.mat 就行了

**Comment by PayneYong** [comment]
还是同样的错误Traceback (most recent call last):
  File "tools/train.py", line 84, in <module>
    main()
  File "tools/train.py", line 80, in main
    train(cfg)
  File "tools/train.py", line 23, in train
    train_loader, val_loader, num_query, num_classes = make_data_loader(cfg)
  File "./data/build.py", line 20, in make_data_loader
    dataset = init_dataset(cfg.DATASETS.NAMES)
  File "./data/datasets/__init__.py", line 25, in init_dataset
    return __factory[name](*args, **kwargs)
  File "./data/datasets/cuhk03.py", line 54, in __init__
    self._check_before_run()
  File "./data/datasets/cuhk03.py", line 95, in _check_before_run
    raise RuntimeError("'{}' is not available".format(self.split_new_det_mat_path))
RuntimeError: '/home/payne/Dataset/L1aoXingyu/cuhk03/cuhk03_new_protocol_config_detected.mat' is not available

![image](https://user-images.githubusercontent.com/7524271/52619739-84130580-2edd-11e9-8bc5-da441bd84e50.png)
我想问下这个文件cuhk03_new_protocol_config_detected.mat是怎么来的

**Comment by L1aoXingyu** [comment]
https://github.com/KaiyangZhou/deep-person-reid/blob/master/DATASETS.md

**Comment by L1aoXingyu** [comment]
你照着这个里面来，下载对应的文件，同时路径按照他的配置应该就可以了

**Comment by PayneYong** [comment]
好的，谢谢楼主
