### ISSUE TITLE
suprising baseline results!!

### ISSUE THREAD

**Issue by BrettLL** [L1aoXingyu/reid_baseline#15]
Your baseline almost achieve the sota results!!
I want to know Which trick is the most important for improving baseline so high?? Thanks~

**Comment by L1aoXingyu** [comment]
There will be a paper submitted to ICCV19 workshop, which is about the bag of tricks in this repo. @michuanhaohao will do a lot of ablation studies to check every trick's contribution.

**Comment by michuanhaohao** [comment]
@BrettLL Please wait our technical report.

**Comment by BrettLL** [comment]
@michuanhaohao  Waiting for your report!!
