### ISSUE TITLE
只使用triplet loss的效果不如sofmax

### ISSUE THREAD

**Issue by ericsqxd** [L1aoXingyu/reid_baseline#17]
我发现只使用triplet loss作为损失函数的话，rank 1只有90.2%，不如softmax loss, 您可以解释一下吗

**Comment by L1aoXingyu** [comment]
正常的呀，只用 metric learning 的话效果确实会差一些，因为每次看到的id太少了，比如batch size=64，每个id取4张图片，那么每个batch才能看到16个id，而用softmax loss，如果random sample的话，每次能看到更多的样本。
