### ISSUE TITLE
mAP computation

### ISSUE THREAD

**Issue by Pandoro** [L1aoXingyu/reid_baseline#18]
From looking at your code, I'm not fully grasping your mAP computation and I am wondering if you ever compared them to the original market-1501 evaluation script? In my experience, results can vary a lot and in order to make a fair comparison, it would be good to ensure that your mAP computation matches the "official" evaluation method and does not skew the results.

**Comment by L1aoXingyu** [comment]
I just borrow the code of mAP computation from this repo [deep-person-reid](https://github.com/KaiyangZhou/deep-person-reid). I think this can match the "official" evaluation. You can check in his repo.

Feel free to ask me if you have any question.

**Comment by Pandoro** [comment]
Hey,

so quick update. I just tried your code and compared it to the results of the official market evaluation. The mAP computation you use, in all cases gives slightly better results. Depending on the experiment, the mAP is overestimated by 0.5%~1.0%, which, given the the difference between some publications seems rather significant!

I think it would make sense to fix this and maybe even update the numbers in your paper.

**Comment by Pandoro** [comment]
Another little addition, especially for the CUHK03-np scores, the difference is even bigger. In the most extreme case I found, the difference is a 2.7% higher mAP value, but typically it is rather between 1.5% and 2%.

**Comment by L1aoXingyu** [comment]
I am sorry to respond to you so late. There is something wrong in CUHK03 mAP computation and I will put a correct version in two or three days. 
For market1501 and duke, I think there is no difference between my evaluation and original evaluation.

**Comment by Pandoro** [comment]
So does that mean you actually produced your embeddings and evaluated them
with the original market code written in matlab?

We made sure our code does exactly the same before we switched form the
matlab code. When I used your mAP computation and compared it to ours,
yours consistently gave better results in all of my experiments.

**Comment by L1aoXingyu** [comment]
This evaluation and mAP computation are from [open reid](https://github.com/Cysu/open-reid). And it has been used for a long time.
The difference between matlab and python maybe comes from computational precision.
As far as I know, almost all papers use this evaluation protocol, and I think it's no problem comparing our results with other papers.

**Comment by Pandoro** [comment]
The evaluation from Open Reid found [here](https://github.com/Cysu/open-reid/blob/master/reid/evaluation_metrics/ranking.py) is actually very different from the one you use found [here](https://github.com/L1aoXingyu/reid_baseline/blob/master/data/datasets/eval_reid.py). It's not  about precision, but the whole computation is completely different. In fact earlier in this exact thread you said yourself that you got the code from [deep-person-reid](https://github.com/KaiyangZhou/deep-person-reid), not from open reid.

Apart from that, the open reid repo uses scikit learn for the AP computation. It should be noted that going forward from scikit learn v0.19 the `average_precision` computation is not the same as the one used by the original market script (again it is slightly too optimistic), but probably most do use that indeed. It still causes some unfair comparisons, but nobody really reports these details.

**Comment by L1aoXingyu** [comment]
Actually, I used the code from [deep-person-reid](https://github.com/KaiyangZhou/deep-person-reid) and I think I can get the same mAP result as open reid though it's different.
But as far as I know, most use open-reid or deep-person-reid, and there is little using matlab code. So I think is fair comparisons.
