### ISSUE TITLE
Support of Video ReID datasets

### ISSUE THREAD

**Issue by alec3010** [L1aoXingyu/reid_baseline#19]
Hi y'all,

I am  benchmarking different ReID-Algorithms for my Thesis on my uni's macchine. I already trained most of them on cuhk and market1501 and i wonder whether i can use the proposed training algorithm on mars(dataset, not the planet :p) as well. I am a novice AI-developer so I'm kind of lacking the experience to develop my own assessment. 

I'd be delighted if someone finds the time to share their insights on feasibiity and necessary steps.

Kind Regards

**Comment by L1aoXingyu** [comment]
I will add mars as soon as possible.

**Comment by qtboi** [comment]
@L1aoXingyu it is not completed
