### ISSUE TITLE
RuntimeError: copy from Parameter to torch.FloatTensor isn't implemented

### ISSUE THREAD

**Issue by YihangLou** [L1aoXingyu/reid_baseline#2]
Dear author:
    could you provide the version of your pytorch used in your code?
Thanks

**Comment by L1aoXingyu** [comment]
0.4

**Comment by YihangLou** [comment]
thanks for.your reply

发自我的 iPhone

在 2018年8月8日，16:10，LiaoXingyu <notifications@github.com<mailto:notifications@github.com>> 写道：


0.4
