### ISSUE TITLE
missing the adabound.py in the "/solver/"

### ISSUE THREAD

**Issue by CHENGY12** [L1aoXingyu/reid_baseline#26]
Hi, Xingyu, thanks for you nice update! If a solver file is missed. I have seen the code in the /solver/__init.__.py, which uses "from .adabound import *", but I can't find the  .adabound .

Looking forward for your reply. Thank you.

**Comment by L1aoXingyu** [comment]
I am sorry, adabound is a trick that I tried to improve performance, but I found it not helpful, So I deleted it. 
I will update the code and then update the README.

**Comment by CHENGY12** [comment]
thank you~

**Comment by L1aoXingyu** [comment]
You can try it now. 
You meet other problems, you can tell me as soon as possible

**Comment by CHENGY12** [comment]
Thank you again! The bug is solved. Btw, the updates include "lighting", ibn ,multi-datasets and so on, If possible, can you provide the ablation results? It will be helpful and instructive.

**Comment by L1aoXingyu** [comment]
The model is training...
I will update this on README when finishing code and training.
