### ISSUE TITLE
Can i help me to use demo.py

### ISSUE THREAD

**Issue by 17702513221** [L1aoXingyu/reid_baseline#28]
When i use python3 demo.py,reid_model.pt does not exist.
please help me to use /logs/market1501/combineall_bs256_mgn_plus/ckpts/model_best.pth
Thank you

**Comment by L1aoXingyu** [comment]
this path is where you put your trained model, and you need to train on datasets, then you can get the pretrained model. Finally, you can use demo to get image feature by using your own pretrained model.

**Comment by 17702513221** [comment]
def __init__(self):

        #self.cfg = self.prepare('config/softmax_triplet.yml')
        # self.num_classes = 413

        self.model = Baseline('resnet50_ibn',100, 1)
        state_dict = torch.load('logs/market1501/combineall_bs256_mgn_plus/ckpts/model_best.pth')
        self.model.load_params_wo_fc(state_dict['model'])
        self.model.cuda()
        self.model.eval()
        # self.model = torch.jit.load("reid_model.pt")
        #self.model.eval()
        #self.model.cuda()
        
        #example = torch.rand(1, 3, 256, 128)
        #example = example.cuda()
        #traced_script_module = torch.jit.trace(self.model, example)
        #raced_script_module.save("reid_model.pt")

    self.model = Baseline('resnet50_ibn',100, 1)
TypeError: __init__() missing 3 required positional arguments: 'with_ibn', 'gcb', and 'stage_with_gcb'

**Comment by 17702513221** [comment]
def __init__(self):

        #self.cfg = self.prepare('config/softmax_triplet.yml')
        # self.num_classes = 413
       # WITH_IBN = False
      #  STAGE_WITH_GCB = (False, False, False, False)
      #  self.model = Baseline('resnet50_ibn',100, 1)
      #  state_dict = torch.load('logs/market1501/combineall_bs256_mgn_plus/ckpts/model_best.pth',,,STAGE_WITH_GCB)
      #  self.model.load_params_wo_fc(state_dict['model'])
      #  self.model.cuda()
      #  self.model.eval()
        self.model = torch.jit.load("logs/market1501/combineall_bs256_mgn_plus/ckpts/model_best.pth")
        #self.model.eval()
        #self.model.cuda()
        
        #example = torch.rand(1, 3, 256, 128)
        #example = example.cuda()
        #traced_script_module = torch.jit.trace(self.model, example)
        #raced_script_module.save("reid_model.pt")

 self.model = torch.jit.load("logs/market1501/combineall_bs256_mgn_plus/ckpts/model_best.pth")
  File "/home/xs/.local/lib/python3.6/site-packages/torch/jit/__init__.py", line 162, in load
    cpp_module = torch._C.import_ir_module(cu, f, map_location, _extra_files)
RuntimeError: [enforce fail at inline_container.cc:137] . PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by L1aoXingyu** [comment]
you need to check what is `torch.jit`, and you can use regular pytorch model at first. I mean you need to define the model, then `model.load_state_dict(torch.load(weight_path))`

**Comment by 17702513221** [comment]
Thank you
