### ISSUE TITLE
RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity

### ISSUE THREAD

**Issue by cendelian** [L1aoXingyu/reid_baseline#30]
Hi L1aoXingyu

when I run command:
bash scripts/train_openset.sh
there have some error as below:

Traceback (most recent call last):
  File "tools/train.py", line 86, in <module>
    main()
  File "tools/train.py", line 70, in main
    reid_system.train()
  File "./engine/trainer.py", line 175, in train
    self.training_step(batch)
  File "./engine/trainer.py", line 85, in training_step
    loss_dict = self.loss_fns(outputs, labels)
  File "./engine/trainer.py", line 53, in loss_fns
    triplet_loss = self.triplet(outputs[1], labels)[0]
  File "/home/cendelian/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "./modeling/losses/triplet_loss.py", line 121, in forward
    dist_ap, dist_an = hard_example_mining(dist_mat, labels)
  File "./modeling/losses/triplet_loss.py", line 75, in hard_example_mining
    dist_mat[is_neg].contiguous().view(N, -1), 1, keepdim=True)
**RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity**

why torch.min() have error, could you help me?

**Comment by cendelian** [comment]
Traceback (most recent call last):
  File "tools/train.py", line 86, in <module>
    main()
  File "tools/train.py", line 70, in main
    reid_system.train()
  File "./engine/trainer.py", line 175, in train
    self.training_step(batch)
  File "./engine/trainer.py", line 85, in training_step
    loss_dict = self.loss_fns(outputs, labels)
  File "./engine/trainer.py", line 53, in loss_fns
    triplet_loss = self.triplet(outputs[1], labels)[0]
  File "/home/cendelian/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "./modeling/losses/triplet_loss.py", line 119, in forward
    dist_ap, dist_an = hard_example_mining(dist_mat, labels)
  File "./modeling/losses/triplet_loss.py", line 73, in hard_example_mining
    **dist_an, relative_n_inds = torch.min(dist_mat[is_neg].contiguous().view(N, -1), 1, keepdim=True)**
**RuntimeError: cannot perform reduction function min on tensor with no elements because the operation does not have an identity**

**Comment by L1aoXingyu** [comment]
what's the version of your pytorch?

**Comment by cendelian** [comment]
> what's the version of your pytorch?

my torch version is 1.2.0 , torchvision is 0.2.2
Could you help me？
I think it make me confuse for several days.

and i add some print some information as below:

`
    print('is_pos is {}'.format(dist_mat[is_pos].contiguous().view(N, -1).shape)) # add by delian
    dist_ap, relative_p_inds = torch.max(dist_mat[is_pos].contiguous().view(N, -1), 1, keepdim=True)

    # `dist_an` means distance(anchor, negative)
    # both `dist_an` and `relative_n_inds` with shape [N, 1]
    print('is_neg is {}'.format(dist_mat[is_neg].contiguous().view(N, -1).shape)) # add by delian
    dist_an, relative_n_inds = torch.min(dist_mat[is_neg].contiguous().view(N, -1), 1, keepdim=True)
`

the print results as below:
is_pos is torch.Size([4, 4])
is_neg is torch.Size([4, 0])

I think the dist_mat[is_neg].contiguous().view(N, -1) is wrong, but I dont know why it isn't [4,4], I didn't do any modification.

**Comment by L1aoXingyu** [comment]
you need to use `triplet` sampler for training triplet loss

**Comment by cendelian** [comment]
> you need to use `triplet` sampler for training triplet loss

I download the data Market-1501 which have bounding_box_train dir , bounding_box_test dir ...

Do you mean that I need to generate triplet sampler according bounding_box_train ?
and how to generate triplet sampler?

**Comment by L1aoXingyu** [comment]
no, just set it in configuration

**Comment by cendelian** [comment]
> no, just set it in configuration, `configs/softmax_triplet.yml`
> Are you training the model through `README`

yes, I am training the model through `README`
and i modify train_open.sh as below:
`CUDA_VISIBLE_DEVICES=$GPUS python tools/train.py -cfg='configs/softmax_triplet.yml' \
DATASETS.NAMES '("market1501",)'  \
DATASETS.TEST_NAMES 'market1501' \
INPUT.SIZE_TRAIN '[256, 128]' \
INPUT.SIZE_TEST '[256, 128]' \
SOLVER.IMS_PER_BATCH '4' \
MODEL.NAME 'baseline' \
MODEL.WITH_IBN 'True' \
MODEL.BACKBONE 'resnet50' \
MODEL.VERSION 'baseline_bs256' \
MODEL.PRETRAIN_PATH '/home/cendelian/.cache/torch/checkpoints/resnet50_ibn_a.pth.tar' \
SOLVER.OPT 'adam' \
SOLVER.LOSSTYPE '("softmax", "triplet")' \


# Original backup by cendelian
# DATASETS.NAMES '("dukemtmc",)'  \
# DATASETS.TEST_NAMES 'dukemtmc' \
# SOLVER.IMS_PER_BATCH '256' \
# MODEL.PRETRAIN_PATH '/export/home/lxy/.cache/torch/checkpoints/resnet50_ibn_a.pth.tar' \`

and the softmax_triplet.ymx is as below:

`MODEL:
  BACKBONE: "resnet50"
  GCB:
    ratio: 0.0625


DATASETS:
  NAMES: ('market1501',)
  TEST_NAMES: "market1501"

DATALOADER:
  SAMPLER: 'triplet'
  NUM_INSTANCE: 4

SOLVER:
  OPT: "adam"
  LOSSTYPE: ('softmax', 'triplet')
  MAX_EPOCHS: 120
  BASE_LR: 0.00035
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [40, 90]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10

  EVAL_PERIOD: 30

TEST:
  IMS_PER_BATCH: 512
  WEIGHT: "path"`


what's wrong i did?

**Comment by cendelian** [comment]
> no, just set it in configuration, `configs/softmax_triplet.yml`
> Are you training the model through `README`

**yes, I am training the model through README
and i modify train_open.sh as below:**
`CUDA_VISIBLE_DEVICES=$GPUS python tools/train.py -cfg='configs/softmax_triplet.yml'
DATASETS.NAMES '("market1501",)'
DATASETS.TEST_NAMES 'market1501'
INPUT.SIZE_TRAIN '[256, 128]'
INPUT.SIZE_TEST '[256, 128]'
SOLVER.IMS_PER_BATCH '4'
MODEL.NAME 'baseline'
MODEL.WITH_IBN 'True'
MODEL.BACKBONE 'resnet50'
MODEL.VERSION 'baseline_bs256'
MODEL.PRETRAIN_PATH '/home/cendelian/.cache/torch/checkpoints/resnet50_ibn_a.pth.tar'
SOLVER.OPT 'adam'
SOLVER.LOSSTYPE '("softmax", "triplet")' \

**and the softmax_triplet.ymx is as below:**

`MODEL:
BACKBONE: "resnet50"
GCB:
ratio: 0.0625

DATASETS:
NAMES: ('market1501',)
TEST_NAMES: "market1501"

DATALOADER:
SAMPLER: 'triplet'
NUM_INSTANCE: 4

SOLVER:
OPT: "adam"
LOSSTYPE: ('softmax', 'triplet')
MAX_EPOCHS: 120
BASE_LR: 0.00035
WEIGHT_DECAY: 0.0005
WEIGHT_DECAY_BIAS: 0.0005
IMS_PER_BATCH: 64

STEPS: [40, 90]
GAMMA: 0.1

WARMUP_FACTOR: 0.01
WARMUP_ITERS: 10

EVAL_PERIOD: 30

TEST:
IMS_PER_BATCH: 512
WEIGHT: "path"`

what's wrong i did?

**Comment by L1aoXingyu** [comment]
why you set `SOLVER.IMS_PER_BATCH '4'`, this means batchsize=4, and with `triplet` sampler, your batch only has 1 ID because every ID has 4 images.

**Comment by cendelian** [comment]
> why you set `SOLVER.IMS_PER_BATCH '4'`, this means batchsize=4, and with `triplet` sampler, your batch only has 1 ID because every ID has 4 images.

Because my gpu memory is not enough, if I set `SOLVER.IMS_PER_BATCH '64` or more, it will display cuda memory error.

By the way, before I modify the config,
**train_open.sh** 's ` SOLVER.IMS_PER_BATCH`(256) is differrent with **softmax_triplet.ymx**'s `SOLVER.IMS_PER_BATCH` (64)

why? there are any difference?

**Comment by L1aoXingyu** [comment]
the only difference is the number of images for every GPU. Maybe you need to train with only softmax, because of your little memory of GPU.
