### ISSUE TITLE
stop train

### ISSUE THREAD

**Issue by zhanghongruiupup** [L1aoXingyu/reid_baseline#32]
this show:
 Epoch 1 Iter 119/186 ce_loss: 6.609 triplet: 2.262 Total loss: 8.870 

It's 119 all the time.

**Comment by L1aoXingyu** [comment]
because 186 is the estimated length of dataloader, you can see it [here](https://github.com/L1aoXingyu/reid_baseline/blob/master/data/samplers/triplet_sampler.py#L38). it's not the actual length, and it may change every time you initialize the dataloader.
