### ISSUE TITLE
basic information gcnet

### ISSUE THREAD

**Issue by Adorablepet** [L1aoXingyu/reid_baseline#34]
Thanks for sharing your codes. I want to ask what is the main reason for this gcnet? I feel that there is an increase in the map, but a decline on the rank. It may also be caused by fluctuations.Do you think that if you add or not, will it affect the network itself?Thanks.

**Comment by L1aoXingyu** [comment]
I just want to test it because it's just like a basic module, such as SE Block.

**Comment by Adorablepet** [comment]
@L1aoXingyu I also try it, and add into my model.The effect is not good.Thanks.
