### ISSUE TITLE
Error: all query identities do not appear in gallery

### ISSUE THREAD

**Issue by cendelian** [L1aoXingyu/reid_baseline#36]
Hi 
when i use market1501 to trian the model .
after 30 epoch and test,
there are some error:
could you help me?

Epoch 29 Iter 78/83 ce_loss: 0.041 triplet: 0.011 Total loss: 0.053  
2019-11-21 14:52:42,903 reid_baseline.train INFO: Epoch 29 Total loss: 0.116 lr: 3.50e-04 During 1min:30s
 Epoch 30 Iter 78/83 ce_loss: 0.030 triplet: 0.015 Total loss: 0.045  
2019-11-21 14:54:13,363 reid_baseline.train INFO: Epoch 30 Total loss: 0.120 lr: 3.50e-04 During 1min:30s
**Traceback (most recent call last):
  File "tools/train.py", line 81, in <module>
    main()
  File "tools/train.py", line 65, in main
    reid_system.train()
  File "./engine/trainer.py", line 178, in train
    metric_dict = self.test()
  File "./engine/trainer.py", line 155, in test
    cmc, mAP = evaluate(-distmat, q_pids, g_pids, q_camids, g_camids)
  File "./data/datasets/eval_reid.py", line 163, in evaluate
    return evaluate_py(distmat, q_pids, g_pids, q_camids, g_camids, max_rank, use_metric_cuhk03)
  File "./data/datasets/eval_reid.py", line 156, in evaluate_py
    return eval_market1501(distmat, q_pids, g_pids, q_camids, g_camids, max_rank)
  File "./data/datasets/eval_reid.py", line 143, in eval_market1501
    assert num_valid_q > 0, "Error: all query identities do not appear in gallery"
AssertionError: Error: all query identities do not appear in gallery**

**Comment by gmt710** [comment]
At least two queries are required.

**Comment by hustzeyu** [comment]
> Hi
> when i use market1501 to trian the model .
> after 30 epoch and test,
> there are some error:
> could you help me?
> 
> Epoch 29 Iter 78/83 ce_loss: 0.041 triplet: 0.011 Total loss: 0.053
> 2019-11-21 14:52:42,903 reid_baseline.train INFO: Epoch 29 Total loss: 0.116 lr: 3.50e-04 During 1min:30s
> Epoch 30 Iter 78/83 ce_loss: 0.030 triplet: 0.015 Total loss: 0.045
> 2019-11-21 14:54:13,363 reid_baseline.train INFO: Epoch 30 Total loss: 0.120 lr: 3.50e-04 During 1min:30s
> **Traceback (most recent call last): File "tools/train.py", line 81, in main() File "tools/train.py", line 65, in main reid_system.train() File "./engine/trainer.py", line 178, in train metric_dict = self.test() File "./engine/trainer.py", line 155, in test cmc, mAP = evaluate(-distmat, q_pids, g_pids, q_camids, g_camids) File "./data/datasets/eval_reid.py", line 163, in evaluate return evaluate_py(distmat, q_pids, g_pids, q_camids, g_camids, max_rank, use_metric_cuhk03) File "./data/datasets/eval_reid.py", line 156, in evaluate_py return eval_market1501(distmat, q_pids, g_pids, q_camids, g_camids, max_rank) File "./data/datasets/eval_reid.py", line 143, in eval_market1501 assert num_valid_q > 0, "Error: all query identities do not appear in gallery" AssertionError: Error: all query identities do not appear in gallery**

Hi, how did you solve the problem?
