### ISSUE TITLE
about distmat

### ISSUE THREAD

**Issue by guanyonglai** [L1aoXingyu/reid_baseline#38]
看到作者把这些都注释掉了
        # distmat = torch.pow(qf, 2).sum(dim=1, keepdim=True).expand(m, n) + \
        #           torch.pow(gf, 2).sum(dim=1, keepdim=True).expand(n, m).t()
        # distmat.addmm_(1, -2, qf, gf.t())
        # distmat = distmat.cpu().numpy()
那么传到后面的distmat就是 distmat = torch.mm(qf, gf.t()).cpu().numpy()，
这仅仅是一个矩阵相乘怎么代替距离矩阵的愣是没看懂啊，

**Comment by L1aoXingyu** [comment]
首先我对 feature 做了 l2 norm，然后内积就和cosine similarity一致，可以推倒一下数学公式
