### ISSUE TITLE
Test time augmentation

### ISSUE THREAD

**Issue by kilsenp** [L1aoXingyu/reid_baseline#6]
Hi,
thanks for your work.

From looking at your code, it seems like the augmentations during training and testing are the same. Is that correct?

Regards

**Comment by L1aoXingyu** [comment]
You can check here https://github.com/L1aoXingyu/reid_baseline/blob/master/core/loader.py#L94
We use test aug for testing.

**Comment by kilsenp** [comment]
Thanks!
